spring:
  cloud:
    gateway:
      routes:
        - id:  servicio-productos
          uri:  lb://servicio-productos
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2    #esto sirve para indicar la cantidad de prefijos en el Path. Es decir, en este caso hay 2 y lo definimos como tal#
        - id: servicio-items
          uri:  lb://servicio-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2     #esto sirve para indicar la cantidad de prefijos en el Path. Es decir, en este caso hay 2 y lo definimos como tal#

